const state={recipes:[],filter:'все',query:'',favorites:new Set(JSON.parse(localStorage.getItem('cozyFavorites')||'[]'))};
const grid=document.getElementById('recipesGrid');const filtersEl=document.getElementById('filters');const searchInput=document.getElementById('searchInput');const modal=document.getElementById('modal');const modalContent=document.getElementById('modalContent');const closeModal=document.getElementById('closeModal');const toast=document.getElementById('toast');
const fallbackImages=["https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=1200&auto=format&fit=crop","https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=1200&auto=format&fit=crop","https://images.unsplash.com/photo-1498837167922-ddd27525d352?q=80&w=1200&auto=format&fit=crop"];
function idOf(r){return r.id||r.title.toLowerCase().replaceAll(' ','-')}function saveFav(){localStorage.setItem('cozyFavorites',JSON.stringify([...state.favorites]))}function showToast(t){toast.textContent=t;toast.classList.remove('hidden');setTimeout(()=>toast.classList.add('hidden'),1600)}
async function init(){try{const base=await fetch('recipes.json?v=4').then(r=>r.json());const custom=JSON.parse(localStorage.getItem('cozyCustomRecipes')||'[]');state.recipes=[...base,...custom]}catch(e){grid.innerHTML='<div class="empty">Рецепты не загрузились. GitHub опять решил быть драматичным.</div>'}renderFilters();renderRecipes();}
function allCategories(){const s=new Set(['все','избранное']);state.recipes.forEach(r=>(r.category||[]).forEach(c=>s.add(c)));return [...s]}
function renderFilters(){filtersEl.innerHTML=allCategories().map(c=>`<button class="filter-btn ${state.filter===c?'active':''}" data-filter="${c}">${c}</button>`).join('');filtersEl.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;renderFilters();renderRecipes();});}
function matches(r){const q=state.query.trim().toLowerCase();const text=[r.title,...(r.category||[]),...(r.ingredients||[])].join(' ').toLowerCase();const byQ=!q||text.includes(q);const byF=state.filter==='все'||(state.filter==='избранное'?state.favorites.has(idOf(r)):(r.category||[]).includes(state.filter));return byQ&&byF}
function renderRecipes(){const list=state.recipes.filter(matches);grid.innerHTML=list.length?list.map(card).join(''):'<div class="empty">Ничего не нашла. Холодильник пока победил.</div>';grid.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openRecipe(b.dataset.open));grid.querySelectorAll('[data-fav]').forEach(b=>b.onclick=(e)=>{e.stopPropagation();toggleFav(b.dataset.fav);});}
function card(r,i){const id=idOf(r);const img=r.image||fallbackImages[i%fallbackImages.length];return `<article class="recipe-card"><div class="image-wrap"><img class="recipe-image" src="${img}" alt="${r.title}" loading="lazy" onerror="this.src='${fallbackImages[i%fallbackImages.length]}'"><button class="favorite-btn ${state.favorites.has(id)?'active':''}" data-fav="${id}">${state.favorites.has(id)?'♥':'♡'}</button></div><div class="recipe-content"><h3 class="recipe-title">${r.title}</h3><div class="recipe-meta">⏱ ${r.time||'—'} · 🔥 ${r.heat||'—'}<br>🍽 ${r.portions||'—'} · ${r.difficulty||'легко, если не паниковать'}</div><div class="tags">${(r.category||[]).map(t=>`<span class="tag">${t}</span>`).join('')}</div><button class="open-btn" data-open="${id}">Открыть рецепт</button></div></article>`}
function toggleFav(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);saveFav();renderRecipes();showToast(state.favorites.has(id)?'Добавлено в избранное':'Убрано из избранного')}
function openRecipe(id){const r=state.recipes.find(x=>idOf(x)===id);if(!r)return;modalContent.innerHTML=`<article class="modal-card"><img class="modal-hero" src="${r.image||fallbackImages[0]}" onerror="this.src='${fallbackImages[0]}'" alt="${r.title}"><div class="modal-body"><h2 class="modal-title">${r.title}</h2><div class="modal-meta">⏱ ${r.time||'—'} · 🔥 ${r.heat||'—'} · 🍽 ${r.portions||'—'} · ${r.difficulty||''}</div><div class="tags">${(r.category||[]).map(t=>`<span class="tag">${t}</span>`).join('')}</div><h3 class="modal-section-title">Ингредиенты</h3><ul class="ingredients-list">${(r.ingredients||[]).map(x=>`<li>${x}</li>`).join('')}</ul><h3 class="modal-section-title">Как готовить</h3><ol class="steps-list">${(r.steps||[]).map(x=>`<li>${x}</li>`).join('')}</ol>${r.tips?.length?`<div class="tips"><b>Советы, чтобы не накосячить:</b><ul>${r.tips.map(x=>`<li>${x}</li>`).join('')}</ul></div>`:''}</div></article>`;modal.classList.remove('hidden');document.body.style.overflow='hidden'}
function closeRecipe(){modal.classList.add('hidden');document.body.style.overflow=''}
closeModal.onclick=closeRecipe;modal.onclick=e=>{if(e.target===modal)closeRecipe()};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeRecipe()});
searchInput.oninput=e=>{state.query=e.target.value;renderRecipes()};document.getElementById('randomBtn').onclick=()=>{const list=state.recipes.filter(matches);const r=list[Math.floor(Math.random()*list.length)]||state.recipes[0];if(r)openRecipe(idOf(r));};document.getElementById('surpriseBtn').onclick=()=>{const quick=state.recipes.filter(r=>(r.category||[]).includes('быстро'));const r=quick[Math.floor(Math.random()*quick.length)]||state.recipes[Math.floor(Math.random()*state.recipes.length)];if(r)openRecipe(idOf(r));};
document.getElementById('pantryBtn').onclick=()=>{const items=document.getElementById('pantryInput').value.toLowerCase().split(',').map(x=>x.trim()).filter(Boolean);if(!items.length){document.getElementById('pantryResult').innerHTML='Впиши хотя бы один продукт. Приложение умное, но не экстрасенс.';return}const scored=state.recipes.map(r=>{const text=(r.ingredients||[]).join(' ').toLowerCase();const score=items.filter(i=>text.includes(i)).length;return{r,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,5);document.getElementById('pantryResult').innerHTML=scored.length?`<b>Можно приготовить:</b><br>${scored.map(x=>`• ${x.r.title} — совпало: ${x.score}`).join('<br>')}`:'Пока ничего не нашла. Возможно, это набор продуктов для квеста, а не ужина.'};
document.getElementById('addRecipeForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const recipe={id:'custom-'+Date.now(),title:f.get('title'),category:(f.get('categories')||'другое').split(',').map(x=>x.trim()).filter(Boolean),image:f.get('image')||fallbackImages[1],time:f.get('time')||'—',heat:f.get('heat')||'—',portions:f.get('portions')||'—',difficulty:f.get('difficulty')||'домашний уровень',ingredients:(f.get('ingredients')||'').split('\n').map(x=>x.trim()).filter(Boolean),steps:(f.get('steps')||'').split('\n').map(x=>x.trim()).filter(Boolean),tips:['Если получилось вкусно — делаем вид, что так и было задумано.']};const custom=JSON.parse(localStorage.getItem('cozyCustomRecipes')||'[]');custom.push(recipe);localStorage.setItem('cozyCustomRecipes',JSON.stringify(custom));state.recipes.push(recipe);e.target.reset();renderFilters();renderRecipes();showToast('Рецепт сохранён на этом устройстве')};
if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js?v=4').catch(()=>{})}init();
