const BASE_RECIPES_URL = 'recipes.json?v=5';
const app = document.getElementById('app');
const bottomNav = document.getElementById('bottomNav');
let recipes = []; let tab='home'; let active='все'; let query=''; let fridge='';
const store = { fav: JSON.parse(localStorage.getItem('cf_fav')||'[]'), custom: JSON.parse(localStorage.getItem('cf_custom')||'[]') };
const norm = s => String(s||'').toLowerCase().replace(/ё/g,'е');
const imgFor = title => `https://source.unsplash.com/900x900/?${encodeURIComponent(title+', food')}`;
function save(){ localStorage.setItem('cf_fav', JSON.stringify(store.fav)); localStorage.setItem('cf_custom', JSON.stringify(store.custom)); }
async function init(){ try{recipes=await fetch(BASE_RECIPES_URL).then(r=>r.json())}catch(e){recipes=[]} recipes=[...recipes,...store.custom]; render(); }
function cats(){ return ['все','избранное','завтрак','быстро','мясо','ужин','паста','рыба','полезное','курица']; }
function matches(r){ const hay = norm([r.title, ...(r.category||[]), ...(r.ingredients||[]), ...(r.steps||[])].join(' ')); const q = norm(query).trim(); const c = active==='все' || (active==='избранное'? store.fav.includes(r.id): (r.category||[]).map(norm).includes(norm(active))); return c && (!q || q.split(/[ ,]+/).every(w=>hay.includes(w))); }
function fridgeMatches(r){ const words = norm(fridge).split(/[,.\n]+/).map(x=>x.trim()).filter(Boolean); if(!words.length) return []; return recipes.filter(r=>{const ing=norm((r.ingredients||[]).join(' ')); return words.some(w=>ing.includes(w));}); }
function filtered(){ let list = recipes.filter(matches); if(tab==='fav') list=list.filter(r=>store.fav.includes(r.id)); return list; }
function nav(){ const items=[['home','🏠','Главная'],['fav','❤️','Избранное'],['fridge','🥕','Дома'],['add','➕','Добавить']]; bottomNav.innerHTML=items.map(i=>`<button class="nav-btn ${tab===i[0]?'active':''}" onclick="tab='${i[0]}';render()"><span>${i[1]}</span>${i[2]}</button>`).join(''); }
function render(){ nav(); app.className='app'; app.innerHTML=`${hero()}${tab==='add'?addForm():controls()}${tab==='fridge'?fridgeBox():''}${tab==='home'?fridgeMini()+grid(filtered()):''}${tab==='fav'?grid(filtered()):''}${tab==='fridge'?grid(fridgeMatches({})) : ''}<div id="modal" class="modal"></div>`; }
function hero(){ return `<section class="hero"><div class="eyebrow">уютный рандомайзер еды</div><h1>Cozy Foodie</h1><p>Нажми кнопку — и приложение решит, что готовить. Без экзистенциального кризиса у холодильника.</p><button class="random" onclick="openRecipe(randomRecipe())">🎲 Случайный рецепт</button></section>` }
function controls(){ return `<input class="search" placeholder="Поиск: паста, курица, яйца..." value="${query}" oninput="query=this.value;render()"><div class="chips">${cats().map(c=>`<button class="chip ${active===c?'active':''}" onclick="active='${c}';render()">${c}</button>`).join('')}</div>` }
function fridgeMini(){ return `<section class="section"><h2>Что есть дома?</h2><p class="muted">Впиши продукты через запятую — покажу, что можно приготовить.</p><textarea class="fridge-input" placeholder="например: яйца, сыр, бекон, паста" oninput="fridge=this.value">${fridge}</textarea><button class="primary" onclick="tab='fridge';render()">🔎 Найти рецепты</button></section>` }
function fridgeBox(){ return `${controls()}<section class="section"><h2>Что есть дома?</h2><p class="muted">Поиск стал умнее: смотрит ингредиенты, категории и шаги.</p><textarea class="fridge-input" placeholder="например: курица, рис, сыр" oninput="fridge=this.value;render()">${fridge}</textarea><p class="results-note">Найдено: ${fridgeMatches({}).length}</p></section>` }
function grid(list){ if(!list.length) return `<p class="results-note">Пока пусто. Либо рецептов мало, либо холодильник сегодня загадочный.</p>`; return `<section class="grid">${list.map(card).join('')}</section>` }
function card(r){ return `<article class="card" onclick="openRecipeById('${r.id}')"><button class="heart ${store.fav.includes(r.id)?'on':''}" onclick="event.stopPropagation();toggleFav('${r.id}')">${store.fav.includes(r.id)?'♥':'♡'}</button><img src="${r.image||imgFor(r.title)}" onerror="this.src='https://placehold.co/900x900/19191d/f5f5f7?text=Cozy+Foodie'" alt=""><div class="card-body"><h3>${r.title}</h3><div class="meta">⏱ ${r.time} · 🔥 ${r.heat}<br>🍽 ${r.portions} · ${r.difficulty}</div><div class="tags">${(r.category||[]).slice(0,3).map(t=>`<span class="tag">${t}</span>`).join('')}</div></div></article>` }
function openRecipeById(id){ openRecipe(recipes.find(r=>r.id===id)); }
function openRecipe(r){ if(!r) return; const m=document.getElementById('modal'); m.classList.add('open'); m.innerHTML=`<button class="close" onclick="closeModal()">×</button><div class="modal-card"><img class="modal-img" src="${r.image||imgFor(r.title)}" onerror="this.src='https://placehold.co/1200x700/19191d/f5f5f7?text=Cozy+Foodie'"><div class="modal-content"><button class="ghost" onclick="toggleFav('${r.id}');openRecipeById('${r.id}')">${store.fav.includes(r.id)?'♥ В избранном':'♡ В избранное'}</button><h2>${r.title}</h2><div class="meta">⏱ ${r.time} · 🔥 ${r.heat} · 🍽 ${r.portions} · ${r.difficulty}</div><div class="tags">${(r.category||[]).map(t=>`<span class="tag">${t}</span>`).join('')}</div><h3>Ингредиенты</h3><ul>${(r.ingredients||[]).map(x=>`<li>${x}</li>`).join('')}</ul><h3>Как готовить</h3><ol>${(r.steps||[]).map(x=>`<li>${x}</li>`).join('')}</ol></div></div>`; }
function closeModal(){ document.getElementById('modal').classList.remove('open'); }
function toggleFav(id){ store.fav = store.fav.includes(id) ? store.fav.filter(x=>x!==id) : [...store.fav,id]; save(); render(); }
function randomRecipe(){ const list=filtered().length?filtered():recipes; return list[Math.floor(Math.random()*list.length)]; }
function addForm(){ return `<section class="section form"><h2>Добавить свой рецепт</h2><p class="muted">Картинку можно вставить ссылкой. Если пусто — попробуем найти фото автоматически по названию.</p><input id="t" placeholder="Название"><input id="cat" placeholder="Категории через запятую: ужин, курица"><input id="time" placeholder="Время: 25 мин"><input id="heat" placeholder="Огонь: 5 из 9"><input id="portions" placeholder="Порции: 2 порц."><input id="diff" placeholder="Сложность: легко"><input id="image" placeholder="Ссылка на картинку, можно пусто"><textarea id="ing" class="textarea" placeholder="Ингредиенты, каждый с новой строки"></textarea><textarea id="steps" class="textarea" placeholder="Шаги, каждый с новой строки. Можно с шутками, мы тут не в санатории."></textarea><button class="primary" onclick="addRecipe()">Сохранить рецепт</button></section>` }
function addRecipe(){ const g=id=>document.getElementById(id).value.trim(); const title=g('t'); if(!title) return alert('Название обязательно, иначе что мы вообще готовим?'); const r={id:'user-'+Date.now(),title,category:g('cat').split(',').map(x=>x.trim()).filter(Boolean),time:g('time')||'—',heat:g('heat')||'—',portions:g('portions')||'—',difficulty:g('diff')||'—',image:g('image')||imgFor(title),ingredients:g('ing').split('\n').map(x=>x.trim()).filter(Boolean),steps:g('steps').split('\n').map(x=>x.trim()).filter(Boolean)}; store.custom.push(r); save(); recipes.push(r); tab='home'; render(); }
init();
