let recipes=[],allRecipes=[],currentFilter="all",visibleCount=30,activeScenario=null,timerInterval=null,timerSecondsLeft=0,timerTotalSeconds=0;
const APP_VERSION="webstable11-scenarios-timers-fridge";
const VISIBLE_STEP=30;
let favorites=JSON.parse(localStorage.getItem("cf_favorites")||"[]"),recent=JSON.parse(localStorage.getItem("cf_recent")||"[]"),shopping=JSON.parse(localStorage.getItem("cf_shopping")||"[]");
const $=id=>document.getElementById(id);
const SCENARIOS={
no_energy:{label:"😭 нет сил",terms:["нет сил","быстро","полуфабрикат","без готовки","лаваш","макароны","пельмени","тост","омлет","салат"],max:25,hint:"Выбрала блюда без подвига. Сегодня кухня работает на режиме энергосбережения."},
fast:{label:"⚡ быстро",terms:["быстро","тост","омлет","лаваш","салат","паста","макароны","яйца"],max:25,hint:"Ищем еду быстрее, чем мозг успеет сказать: ‘может доставку?’"},
cozy:{label:"💛 уютное",terms:["уютное","суп","картошка","каша","котлет","гречка","пюре","сырный","туш"],max:60,hint:"Еда-одеяло включена: тёплая, домашняя, без экзамена по кулинарии."},
soup:{label:"🥣 хочу суп",terms:["суп","бульон","лапша","фрикадель","сырный"],max:60,hint:"Суп — это когда организм попросил заботу в жидком формате."},
cheesy:{label:"🧀 сырное",terms:["сыр","сырное","сливки","сливочный","плавленый"],max:45,hint:"Сырное найдено. Всё, что тянется, уже повышает качество жизни."},
sweet:{label:"🍫 сладкое",terms:["сладкое","сырники","десерт","ягоды","банан","каша","мёд","творог"],max:45,hint:"Сладкое — это не слабость, это эмоциональная логистика."},
light:{label:"🥗 полегче",terms:["пп","лёгкое","салат","овощ","без мяса","творог","булгур","рыба"],max:40,hint:"Полегче, но без вкуса мокрого картона. Лиса не зверь."},
series:{label:"🎬 под сериал",terms:["быстро","лаваш","пельмени","тост","макароны","сырное","нет сил","сосиски"],max:25,hint:"Под сериал нужно то, что удобно есть и не требует паузы на кухонную драму."}
};
function save(){localStorage.setItem("cf_favorites",JSON.stringify(favorites));localStorage.setItem("cf_recent",JSON.stringify(recent));localStorage.setItem("cf_shopping",JSON.stringify(shopping))}
function safeParse(key){try{return JSON.parse(localStorage.getItem(key)||"[]")}catch(e){return[]}}
function normalizeRecipe(r,i){return{id:r.id||`r${i}`,title:r.title||"Без названия",time:r.time||"25 мин",heat:r.heat||r.difficulty||"5 из 9",portions:r.portions||"2 порц.",difficulty:r.difficulty||"средне",image:r.image||makeImg(r.emoji||"🍽️"),emoji:r.emoji||"🍽️",category:Array.isArray(r.category)?r.category:(r.categories||["ужин"]),badges:r.badges||[],ingredients:r.ingredients||[],steps:r.steps||[]}}
function makeImg(emoji){return `data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%201200%201200'%3E%3Crect%20width='1200'%20height='1200'%20fill='%23201820'/%3E%3Ccircle%20cx='250'%20cy='220'%20r='170'%20fill='%23ff7a59'%20opacity='.22'/%3E%3Ctext%20x='600'%20y='635'%20font-size='300'%20text-anchor='middle'%3E${encodeURIComponent(emoji)}%3C/text%3E%3Ctext%20x='600'%20y='870'%20font-family='Arial'%20font-size='54'%20font-weight='900'%20fill='white'%20text-anchor='middle'%3ECozy%20Foodie%3C/text%3E%3C/svg%3E`}
async function loadRecipes(){try{let res=await fetch(`recipes.json?v=${APP_VERSION}`);let data=await res.json();recipes=data.map(normalizeRecipe);allRecipes=[...recipes,...getUserRecipes()]}catch(e){console.error(e);allRecipes=getUserRecipes()}renderAll();updateFloatingRandom()}
function getUserRecipes(){return safeParse("cf_user_recipes").map(normalizeRecipe)}
function recipeHay(r){return [r.title,...(r.category||[]),...(r.ingredients||[]),...(r.steps||[])].join(" ").toLowerCase()}
function parseMinutes(time){let nums=String(time||"").match(/\d+/g);return nums?Math.max(...nums.map(n=>parseInt(n,10)).filter(Boolean),1):10}
function scenarioScore(r,name){let s=SCENARIOS[name];if(!s)return 0;let hay=recipeHay(r),score=0;s.terms.forEach(t=>{if(hay.includes(t.toLowerCase()))score+=2});let m=parseMinutes(r.time);if(s.max&&m<=s.max)score+=1;if(name==="no_energy"&&m<=20)score+=2;if(name==="fast"&&m<=20)score+=2;if(name==="soup"&&hay.includes("суп"))score+=5;if(name==="sweet"&&(hay.includes("слад")||hay.includes("десерт")||hay.includes("сырник")))score+=4;if(name==="cheesy"&&(hay.includes("сыр")||hay.includes("слив")))score+=4;return score}
function getScenarioRecipes(name){let scored=allRecipes.map(r=>({r,score:scenarioScore(r,name)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);if(scored.length<3){scored=allRecipes.map(r=>({r,score:parseMinutes(r.time)<=30?1:0})).filter(x=>x.score>0)}return scored.map(x=>x.r)}
function getFiltered(){let q=($("searchInput")?.value||"").trim().toLowerCase();let scenarioIds=null;if(activeScenario)scenarioIds=new Set(getScenarioRecipes(activeScenario).map(r=>r.id));return allRecipes.filter(r=>{let hay=recipeHay(r);let byText=!q||hay.includes(q);let byFilter=currentFilter==="all"||hay.includes(currentFilter.toLowerCase());let byScenario=!scenarioIds||scenarioIds.has(r.id);return byText&&byFilter&&byScenario})}
function renderAll(){renderHome();renderFavorites();renderRecent();renderShopping()}
function renderHome(){let filtered=getFiltered(),visible=filtered.slice(0,visibleCount);$("countText").textContent=activeScenario?`${filtered.length} по настроению`:`${filtered.length} рецептов`;renderGrid(visible,"recipeGrid");let btn=$("loadMoreBtn");if(btn)btn.style.display=filtered.length>visibleCount?"block":"none"}
function renderGrid(list,id){let grid=$(id);if(!grid)return;if(!list.length){grid.innerHTML=`<div class="panel"><p class="muted">Пока пусто. Лиса покопалась в холодильнике и тоже удивилась.</p></div>`;return}grid.innerHTML=list.map(r=>`<article class="card" data-id="${r.id}"><img src="${r.image||makeImg(r.emoji)}" alt="" loading="lazy" onerror="this.outerHTML='<div class=&quot;card-img-fallback&quot;>${r.emoji}</div>'"><div class="card-actions"><button class="icon-btn fav-btn" data-id="${r.id}">${favorites.includes(r.id)?"♥":"♡"}</button><button class="icon-btn cart-btn" data-id="${r.id}">🛒</button></div><div class="card-body"><h3>${r.title}</h3><div class="meta">⏱ ${r.time} · 🔥 ${r.heat}</div><div class="tags">${(r.category||[]).slice(0,3).map(t=>`<span class="tag">${t}</span>`).join("")}</div></div></article>`).join("")}
function setFilter(filter){currentFilter=filter;activeScenario=null;visibleCount=30;document.querySelectorAll(".chip").forEach(b=>b.classList.toggle("active",b.dataset.filter===filter));document.querySelectorAll(".quick-wishes button").forEach(b=>b.classList.remove("active"));let hint=$("wishHint");if(hint)hint.innerHTML=`<span>Лиса советует:</span> фильтр включён. Если что — кнопка “все” спасает отношения с ужином.`;renderHome()}
function applyScenario(name){activeScenario=name;currentFilter="all";visibleCount=30;document.querySelectorAll(".chip").forEach(b=>b.classList.toggle("active",b.dataset.filter==="all"));document.querySelectorAll(".quick-wishes button").forEach(b=>b.classList.toggle("active",b.dataset.scenario===name));let input=$("searchInput");if(input)input.value="";let s=SCENARIOS[name];let hint=$("wishHint");if(hint)hint.innerHTML=`<span>Лиса советует:</span> ${s?.hint||"Подбираю что-то съедобное."}`;renderHome();openScenarioModal(name)}
function openScenarioModal(name){let s=SCENARIOS[name],list=getScenarioRecipes(name).slice(0,8);$("modalInner").innerHTML=`<div class="modal-content scenario-modal"><h2>${s?.label||"Подборка"}</h2><p class="muted">${s?.hint||"Вот что можно приготовить сейчас."}</p><div class="scenario-result-grid">${list.map(r=>`<article class="mini-recipe" data-id="${r.id}"><div class="mini-emoji">${r.emoji}</div><div><h3>${r.title}</h3><p>⏱ ${r.time} · 🔥 ${r.heat}</p></div></article>`).join("")}</div><button class="ghost full" onclick="closeModal()">Закрыть и смотреть список на главной</button></div>`;$("modal").classList.add("open")}
function clearScenario(){activeScenario=null;document.querySelectorAll(".quick-wishes button").forEach(b=>b.classList.remove("active"))}
function loadMore(){visibleCount+=VISIBLE_STEP;renderHome()}
function randomRecipe(){let list=getFiltered();if(list.length)openRecipe(list[Math.floor(Math.random()*list.length)].id)}
function formatTimer(s){let m=Math.floor(s/60),sec=s%60;return `${String(m).padStart(2,"0")}:${String(sec).padStart(2,"0")}`}
function setupTimer(minutes){timerTotalSeconds=minutes*60;timerSecondsLeft=timerTotalSeconds;updateTimerDisplay()}
function updateTimerDisplay(){let d=$("timerDisplay");if(d)d.textContent=formatTimer(timerSecondsLeft)}
function setTimer(minutes,start=false){pauseTimer();setupTimer(minutes);if(start)startTimer()}
function startTimer(){if(timerInterval)return;if(timerSecondsLeft<=0)timerSecondsLeft=timerTotalSeconds||600;updateTimerDisplay();timerInterval=setInterval(()=>{timerSecondsLeft=Math.max(0,timerSecondsLeft-1);updateTimerDisplay();if(timerSecondsLeft<=0){clearInterval(timerInterval);timerInterval=null;let d=$("timerDisplay");if(d)d.textContent="готово ✨"}},1000)}
function pauseTimer(){if(timerInterval){clearInterval(timerInterval);timerInterval=null}}
function resetTimer(){pauseTimer();timerSecondsLeft=timerTotalSeconds||600;updateTimerDisplay()}
function extractMinutes(text){let nums=String(text||"").match(/\d+/g);return nums?Math.max(...nums.map(n=>parseInt(n,10)).filter(Boolean)):null}
function stepAction(step){let s=step.toLowerCase();if(s.includes("жар"))return "жарить";if(s.includes("туш"))return "тушить";if(s.includes("вар"))return "варить";if(s.includes("запе"))return "запекать";if(s.includes("охлад"))return "охладить";if(s.includes("замороз"))return "заморозить";if(s.includes("накрой")||s.includes("крыш"))return "под крышкой";if(s.includes("прогрей"))return "прогреть";return "этап"}
function getStageTimers(r){let timers=[];(r.steps||[]).forEach((st,i)=>{let mins=extractMinutes(st);if(mins)timers.push({label:`${i+1}. ${stepAction(st)}`,minutes:mins})});let hay=recipeHay(r);if(!timers.length){if(hay.includes("суп")||hay.includes("туш"))timers=[{label:"проверить через",minutes:10},{label:"довести вкус",minutes:15},{label:"мягко потушить",minutes:20}];else if(hay.includes("жар")||hay.includes("котлет")||hay.includes("драник"))timers=[{label:"первая сторона",minutes:5},{label:"вторая сторона",minutes:5},{label:"дойти под крышкой",minutes:3}];else if(hay.includes("слад")||hay.includes("сырник"))timers=[{label:"первая сторона",minutes:4},{label:"вторая сторона",minutes:4},{label:"отдохнуть",minutes:3}];else timers=[{label:"быстрый чек",minutes:5},{label:"средний этап",minutes:10},{label:"контроль готовности",minutes:15}]}return timers.slice(0,6)}
function recipeFact(r){let hay=recipeHay(r);if(hay.includes("суп"))return "Супы часто вкуснее через 10 минут после готовки: вкус успевает собраться, как ты после выходных.";if(hay.includes("сыр"))return "Сыр лучше добавлять ближе к концу: так он плавится, а не превращается в резиновый квест.";if(hay.includes("карто"))return "Картошку солят ближе к концу жарки: так она меньше разваливается и держит корочку.";if(hay.includes("куриц"))return "Курицу не мучай вечной жаркой: после готовности дай ей пару минут отдохнуть, будет сочнее.";if(hay.includes("яйц"))return "Яйца любят средний огонь: на максимуме они быстро становятся резиновыми и начинают мстить.";if(hay.includes("паста")||hay.includes("макарон"))return "Пасту лучше смешивать с соусом на сковороде: так она впитывает вкус, а не просто лежит рядом.";if(hay.includes("слад"))return "В сладком щепотка соли усиливает вкус. Да, это маленькая магия, а не ошибка.";return "Главный факт: еда не обязана быть идеальной. Она обязана помочь тебе не превратиться в злую печеньку."}
function lisaNote(r){let hay=recipeHay(r);if(hay.includes("нет сил")||hay.includes("быстро"))return "Комментарий Лисы: это блюдо не просит от тебя быть героиней дня. Просто сделай и поешь.";if(hay.includes("уют"))return "Комментарий Лисы: уровень уюта высокий, можно есть в пледе и никому ничего не объяснять.";if(hay.includes("пп")||hay.includes("лёгкое"))return "Комментарий Лисы: полезно — не значит грустно. Мы не варим наказание в кастрюле.";return "Комментарий Лисы: если получилось не идеально — называем это авторской подачей и двигаемся дальше."}
function stepDetail(step,r,i){let s=step.toLowerCase();if(s.includes("жар"))return "Сковорода должна быть уже тёплой. Масло — блестит, но не дымит. Если шипит слишком агрессивно, убавь огонь на 1 деление.";if(s.includes("туш"))return "Тушим под крышкой и не открываем каждые 20 секунд: пару раз перемешать достаточно. Если сухо — добавь 2–3 ст. л. воды.";if(s.includes("вар"))return "После закипания убавь огонь, чтобы не было вулкана. Пена/крахмал — не катастрофа, просто сними или перемешай.";if(s.includes("смеш"))return "Сначала смешай мягкие/жидкие компоненты, потом добавляй сухие. Так меньше комков и меньше желания всё бросить.";if(s.includes("сыр"))return "Сыр добавляй на умеренном огне: на максимуме он может пойти комками и обидеться.";if(s.includes("нареж"))return "Режь примерно одинаково: так всё приготовится одновременно, а не будет ‘одна картошка сырая, другая уже пенсионер’.";if(s.includes("накрой")||s.includes("крыш"))return "Крышка нужна, чтобы тепло дошло внутрь. Если снизу быстро темнеет — огонь ниже, терпение выше.";return "Двигайся спокойно: подготовь следующий ингредиент заранее, держи огонь средним и пробуй по ходу. Ты не на экзамене."}
function stepMistake(step){let s=step.toLowerCase();if(s.includes("жар"))return "Ошибка: слишком часто переворачивать. Дай корочке схватиться, потом уже спасай мир.";if(s.includes("вар"))return "Ошибка: варить на максимуме всё время. Так еда разваливается и убегает из кастрюли.";if(s.includes("туш"))return "Ошибка: забыть жидкость. Тушение любит немного влаги и спокойствие.";if(s.includes("сыр"))return "Ошибка: кипятить сырный соус. Лучше тихий огонь и нежное помешивание.";return "Ошибка: пытаться идеально. Лучше вкусно и спокойно, чем красиво и с нервным тиком."}
function renderDetailedSteps(r){return (r.steps||[]).map((st,i)=>`<div class="step-card"><div class="step-num">${i+1}</div><div><strong>${st}</strong><p>${stepDetail(st,r,i)}</p><div class="mistake">⚠️ ${stepMistake(st)}</div></div></div>`).join("")}
function renderTimerButtons(r){let stage=getStageTimers(r);let classic=[3,5,10,15,20];return `<div class="timer-presets"><h3>⏲️ Таймеры по рецепту</h3><div class="timer-chip-row">${stage.map(t=>`<button class="timer-chip" onclick="setTimer(${t.minutes},true)">${t.label}: ${t.minutes} мин</button>`).join("")}</div><h3>Классические</h3><div class="timer-chip-row">${classic.map(m=>`<button class="timer-chip ghost" onclick="setTimer(${m},true)">${m} мин</button>`).join("")}</div></div>`}
function openRecipe(id){let r=allRecipes.find(x=>x.id===id);if(!r)return;recent=[id,...recent.filter(x=>x!==id)].slice(0,20);save();let mins=parseMinutes(r.time);pauseTimer();$("modalInner").innerHTML=`<img class="modal-img" src="${r.image||makeImg(r.emoji)}" alt=""><div class="modal-content"><h2>${r.title}</h2><p class="muted">⏱ ${r.time} · 🔥 ${r.heat} · 🍽 ${r.portions}</p><div class="timer-box"><div><div class="timer-label">Активный таймер</div><div id="timerDisplay" class="timer-display">${formatTimer(mins*60)}</div></div><div class="timer-actions"><button class="secondary" onclick="startTimer()">старт</button><button class="ghost" onclick="pauseTimer()">пауза</button><button class="ghost" onclick="resetTimer()">сброс</button></div></div>${renderTimerButtons(r)}<div class="fox-note">🦊 ${lisaNote(r)}</div><div class="food-fact">💡 ${recipeFact(r)}</div><button class="primary full" onclick="addIngredients('${r.id}')">🛒 Добавить ингредиенты в список</button><h3>Ингредиенты</h3>${(r.ingredients||[]).map(x=>`<label class="ingredient-row"><input type="checkbox"><span>${x}</span></label>`).join("")}<h3>Как готовить подробно</h3><div class="detailed-steps">${renderDetailedSteps(r)}</div></div>`;$("modal").classList.add("open");setupTimer(mins)}
function closeModal(){pauseTimer();$("modal").classList.remove("open")}
function toggleFavorite(id){favorites=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];save();renderAll()}
function addIngredients(id){let r=allRecipes.find(x=>x.id===id);if(!r)return;(r.ingredients||[]).forEach(x=>{if(!shopping.some(item=>item.text===x))shopping.push({text:x,done:false})});save();renderShopping()}
function renderFavorites(){renderGrid(allRecipes.filter(r=>favorites.includes(r.id)),"favoritesGrid")}
function renderRecent(){renderGrid(recent.map(id=>allRecipes.find(r=>r.id===id)).filter(Boolean),"recentGrid")}
function addFridgeIngredient(word){let input=$("fridgeInput");if(!input)return;let items=input.value.split(",").map(x=>x.trim()).filter(Boolean);if(!items.some(x=>x.toLowerCase()===word.toLowerCase()))items.push(word);input.value=items.join(", ");findByIngredients()}
function findByIngredients(){let words=($("fridgeInput").value||"").toLowerCase().split(",").map(x=>x.trim()).filter(Boolean);let found=!words.length?[]:allRecipes.filter(r=>{let hay=(r.ingredients||[]).join(" ").toLowerCase();return words.some(w=>hay.includes(w))}).slice(0,60);renderGrid(found,"fridgeGrid")}
function renderShopping(){let box=$("shopList");if(!box)return;box.innerHTML=shopping.map((item,i)=>`<div class="shop-item ${item.done?"done":""}"><input type="checkbox" ${item.done?"checked":""} onchange="toggleShop(${i})"><span>${item.text}</span><button class="ghost" onclick="removeShop(${i})">×</button></div>`).join("")}
function toggleShop(i){shopping[i].done=!shopping[i].done;save();renderShopping()}
function removeShop(i){shopping.splice(i,1);save();renderShopping()}
function addShopManual(){let input=$("shopInput"),text=input.value.trim();if(!text)return;shopping.push({text,done:false});input.value="";save();renderShopping()}
function clearBought(){shopping=shopping.filter(x=>!x.done);save();renderShopping()}
function clearShop(){shopping=[];save();renderShopping()}
function addRecipe(){let title=$("newTitle").value.trim();if(!title)return alert("Название нужно, Лиса без названия грустит.");let emoji="🍽️";let r={id:"user_"+Date.now(),title,category:$("newCats").value.split(",").map(x=>x.trim()).filter(Boolean),time:$("newTime").value||"25 мин",heat:"5 из 9",portions:"2 порц.",emoji,image:$("newImage").value||makeImg(emoji),ingredients:$("newIngr").value.split("\n").map(x=>x.trim()).filter(Boolean),steps:$("newSteps").value.split("\n").map(x=>x.trim()).filter(Boolean)};let user=safeParse("cf_user_recipes");user.push(r);localStorage.setItem("cf_user_recipes",JSON.stringify(user));allRecipes.push(normalizeRecipe(r));alert("Рецепт добавлен!");showTab("home");renderAll()}
function updateFloatingRandom(){let btn=$("floatingRandomBtn"),home=$("homeTab");if(btn&&home)btn.style.display=home.classList.contains("active")?"":"none"}
function showTab(tab){document.querySelectorAll(".tab").forEach(el=>el.classList.remove("active"));document.querySelectorAll(".nav-btn").forEach(el=>el.classList.remove("active"));let map={home:"homeTab",favorites:"favoritesTab",again:"againTab",fridge:"fridgeTab",shopping:"shoppingTab",add:"addTab"};$(map[tab]).classList.add("active");document.querySelector(`.nav-btn[data-tab="${tab}"]`)?.classList.add("active");document.querySelectorAll(".home-only").forEach(el=>el.style.display=tab==="home"?"":"none");if(tab==="favorites")renderFavorites();if(tab==="again")renderRecent();if(tab==="shopping")renderShopping();updateFloatingRandom();scrollTo({top:0,behavior:"smooth"})}
document.addEventListener("click",e=>{let scenario=e.target.closest(".quick-wishes button");if(scenario)return applyScenario(scenario.dataset.scenario);let ing=e.target.closest(".ingredient-chip");if(ing)return addFridgeIngredient(ing.dataset.ing);let nav=e.target.closest(".nav-btn");if(nav)return showTab(nav.dataset.tab);let fav=e.target.closest(".fav-btn");if(fav)return toggleFavorite(fav.dataset.id);let cart=e.target.closest(".cart-btn");if(cart)return addIngredients(cart.dataset.id);let card=e.target.closest(".card,.mini-recipe");if(card&&!e.target.closest("button"))return openRecipe(card.dataset.id)});
$("randomBtn").onclick=randomRecipe;$("floatingRandomBtn").onclick=randomRecipe;$("loadMoreBtn").onclick=loadMore;$("searchInput").addEventListener("input",()=>{clearScenario();visibleCount=30;renderHome()});$("searchBtn").onclick=()=>{clearScenario();visibleCount=30;renderHome()};$("fridgeBtn").onclick=findByIngredients;$("shopAddBtn").onclick=addShopManual;$("clearDoneBtn").onclick=clearBought;$("clearAllBtn").onclick=clearShop;$("addRecipeBtn").onclick=addRecipe;$("closeModal").onclick=closeModal;document.querySelectorAll(".chip").forEach(btn=>btn.onclick=()=>setFilter(btn.dataset.filter));if("serviceWorker"in navigator)navigator.serviceWorker.getRegistrations().then(regs=>regs.forEach(reg=>reg.unregister()));if(window.caches&&caches.keys)caches.keys().then(keys=>keys.forEach(k=>caches.delete(k)));loadRecipes();document.addEventListener("error",function(e){const t=e.target;if(t&&t.tagName==="IMG"){t.onerror=null;t.outerHTML=`<div class="card-img-fallback">🍽️</div>`}},true);